# SQLite Datenbank unter data/auftrag.db
spring.datasource.url=jdbc:sqlite:data/auftrag.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Server
server.port=8080
server.servlet.context-path=/harald

# Statische Ressourcen (Frontend)
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.add-mappings=true
