name: Build

on:
  push:
  workflow_call:
    inputs:
      upload-jar:
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - uses: pnpm/action-setup@v6
        with:
          version: 11
          cache: true
          cache_dependency_path: frontend/pnpm-lock.yaml

      - name: Cache Gradle wrapper and dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload JAR
        if: github.event_name == 'workflow_call' && inputs.upload-jar
        uses: actions/upload-artifact@v4
        with:
          name: Auftragsmanager
          path: build/libs/Auftragsmanager-*.jar
